### ISSUE TITLE
Containerised deployment of mini-apps

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/react-sci-components#7]
Our first mini-app should soon be ready to we need to look into deploying these.
Probably a simple nginx container should be sufficient.
No authentication needed at this stage, but trusted certs are needed.
We'll deploy to a sub-domain of `informaticsmatters.com`.

**Comment by alanbchristie** [comment]
What container image name would you like to produce? Intuitively I'd guess the same as the project name? i.e. `react-sci-components:latest` for example?

**Comment by tdudgeon** [comment]
@alanbchristie Let's call it `im-mini-apps` for now.

**Comment by alanbchristie** [comment]
Docker changes (npm-yarm) merged
